Move status check before token extraction on empty conditions
adespresso/FeatureBundle pull request #46
Opened 2019-01-18 09:38 UTC by EmanueleMinotto

2019-02-15 09:33 UTC, massimo-me approved these changes

2019-02-15 10:55 UTC, giorrrgio requested changes

2019-02-15 10:55 UTC, giorrrgio commented on Security/FeatureSecurity.php
> +        if (empty($feature->getRole()) && empty($feature->getParentRole())) {
I think that you can delegate this two check to the feature entity: something like `hasRolesAttached`that checks on the feature itself and on the parent (the code is a draft, please double check):
```
class Feature
{
    public function hasRolesAttached()
    {
        return $this->role || $this->parentHasRolesAttached();
    }

    private function parentHasRolesAttached()
    {
        return $this->parent && $this->parent->hasRolesAttached();
    }
}
```

2019-02-25 16:41 UTC, giorrrgio approved these changes

2019-02-25 20:41 UTC, merged